python cluster_syntenic_paths.py achine.bed 2 > achine.2n.subgenomes.bed
python cluster_syntenic_paths.py ccitra.bed 2 > ccitra.2n.subgenomes.bed
python cluster_syntenic_paths.py smicro.bed 2 > smicro.2n.subgenomes.bed
python cluster_syntenic_paths.py agerar.bed 3 > agerar.3n.subgenomes.bed
python cluster_syntenic_paths.py blagur.bed 3 > blagur.3n.subgenomes.bed
python cluster_syntenic_paths.py crefra.bed 1 > crefra.1n.subgenomes.bed
python cluster_syntenic_paths.py etrips.bed 2 > etrips.2n.subgenomes.bed
python cluster_syntenic_paths.py hcompr.bed 6 > hcompr.6n.subgenomes.bed
python cluster_syntenic_paths.py hconto.bed 4 > hconto.4n.subgenomes.bed
python cluster_syntenic_paths.py sscopa.bed 2 > sscopa.2n.subgenomes.bed
python cluster_syntenic_paths.py snutan.bed 2 > snutan.2n.subgenomes.bed
python cluster_syntenic_paths.py ttrian.bed 1 > ttrian.1n.subgenomes.bed
python cluster_syntenic_paths.py udigit.bed 3 > udigit.3n.subgenomes.bed
python cluster_syntenic_paths.py vcuspi.bed 1 > vcuspi.1n.subgenomes.bed
python cluster_syntenic_paths.py aburma.bed 2 > aburma.2n.subgenomes.bed
python cluster_syntenic_paths.py irugos.bed 1 > irugos.1n.subgenomes.bed
python cluster_syntenic_paths.py ppanic.bed 1 > ppanic.1n.subgenomes.bed
python cluster_syntenic_paths.py rrottb.bed 2 > rrottb.2n.subgenomes.bed
python cluster_syntenic_paths.py rtuber.bed 1 > rtuber.1n.subgenomes.bed
python cluster_syntenic_paths.py telega.bed 2 > telega.2n.subgenomes.bed
python cluster_syntenic_paths.py avirgi.bed 1 > avirgi.1n.subgenomes.bed
python cluster_syntenic_paths.py sbicol.bed 1 > sbicol.1n.subgenomes.bed
